### ISSUE TITLE
Failed to parse mod file

### ISSUE THREAD

**Issue by Dvginkel** [Senth/minecraft-mod-manager#131]
### Describe the bug 

After running mmm list or mcman list on the current dir /mods i got following error message:

Failed to parse mod file Hwyla-forge-1.10.11-B78_1.16.2.jar
Traceback (most recent call last):
  File "/home/dennis/.local/lib/python3.8/site-packages/minecraft_mod_manager/gateways/jar_parser.py", line 49, in _get_mod_info
    mod = JarParser._parse_forge(zip)
  File "/home/dennis/.local/lib/python3.8/site-packages/minecraft_mod_manager/gateways/jar_parser.py", line 85, in _parse_forge
    obj = toml.loads(full_doc)
  File "/home/dennis/.local/lib/python3.8/site-packages/toml/decoder.py", line 340, in loads
    raise TomlDecodeError("Unbalanced quotes", original, i)
toml.decoder.TomlDecodeError: Unbalanced quotes (line 12 column 113 char 402)

!!! Please report this and paste the above message !!!

### Steps to reproduce
1) cd /home/user/server/minecraft_server/mods
2) ran mcman list
3) got above message
4) rest of out put showed mod names with questionmarks on the published column

### Expected Behavior
i expected to get a list of installed mods

### Info
 - OS:  Ubuntu 20.04.3 LTS
 - Python --version: Python 3.8.10
 - minecraft-mod-manager --version: 1.2.4

**Comment by Senth** [comment]
Hi @Dvginkel,

Thanks for reporting 🙂 It always helps a lot when people submit bugs. I found some inspiration today to fix the bug 🙂 I will release version 1.2.5 in a few minutes after all tests have completed 🙂 

The issue was that Hwyla uses an invalid syntax in their TOML-file. Namely, the multiline description is using single quotes instead of triple quotes.
```toml
description = "Invalid
multiline comment"
```
but should be
```toml
description = """Valid
multiline comment"""
