### ISSUE TITLE
JSONDecodeError because Modrinth API sends access denied

### ISSUE THREAD

**Issue by Netspider** [Senth/minecraft-mod-manager#150]
Hello,

I am getting a JSONDecodeError in /gateways/downloader.py", line 21
response.text includes this:
**The owner of this website (api.modrinth.com) has banned your access based on your browser's signature (6dd0f3ad096a58e4-ua53).**
Using firefox on api.modrinth.com works so I think they are blocking the python useragent?
Being able to disable one of the API providers would be nice - and a proper error message ;-)

**Comment by Netspider** [comment]
I commented line 31 in .local/lib/python3.8/site-packages/minecraft_mod_manager/adapters/repo_impl.py so that I could atleast use the curse api.

**Comment by theofficialgman** [comment]
I am also having this issue.
@Geometrically could you be so kind as to check on this for us? looks like api.modrinth.com has been blocking this script.
Is this intentional?

**Comment by Geometrically** [comment]
Recently, our API was attacked to bot downloads.

Is this program using the api/v1/version_file/<hash>/download route?

If so, please remove usage of these routes. They are only meant to be used in the browser (to prevent botting) and **will** be blocked by CloudFlare.

To replace usage, use the route without the trailing download /api/v1/version_file/hash and download the first file or one that is marked primary.

If not, then LMK. I might have misconfigured something.

**Comment by Senth** [comment]
Hi, sorry for the late reply. I'll have a look at this tomorrow and hopefully be out with a fix 🙂

**Comment by Senth** [comment]
Version 1.2.6 should now be released that includes this fix 🙂 

Thanks for waiting even though I might be a bit unresponsive at times 😅 

For those interested in what the error was.

I use a specific `User-Agent` from Chrome. This is because of CurseForge does not allow any bots essentially. So this is a way to circumvent that. That user agent was quite old now and Cloudfare probably determined that no one uses that old User-Agent except bots.

The fix I did was only changing the User-Agent when calling CurseForge and leaving it untouched calling Modrith so this hopefully won't happen in the future 🙂

**Comment by theofficialgman** [comment]
@Senth thanks for the update, works fine

I am running into an issue with reading the version output from the script though
I'm attempting to get the current version of the script with `mmm --version | awk '{print $2}'` which prints in bold text 1.2.6
however, every command I pipe this into reports an invalid first number (the rest of the numbers 2 and 6 are fine).
any ideas?
```
dpkg --compare-versions $(mmm --version | awk '{print $2}') "le" "1.2.6"

dpkg: warning: version '1.2.6' has bad syntax: version number does not start with digit
```

**Comment by Senth** [comment]
I created a feature request from your enhancement, @theofficialgman. I think it makes sense to remove the bold from the output. I added it there to be more visible but didn't think of the case where you pipe the output 👍

**Comment by kevinwchang** [comment]
I'm having a similar-looking problem now trying to install/update anything from modrinth:
```
Failed to parse mod file fabric-api-0.47.8+1.18.2.jar
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/minecraft_mod_manager/gateways/jar_parser.py", line 46, in _get_mod_info
    with ZipFile(file, "r") as zip:
  File "/usr/lib/python3.9/zipfile.py", line 1257, in __init__
    self._RealGetContents()
  File "/usr/lib/python3.9/zipfile.py", line 1324, in _RealGetContents
    raise BadZipFile("File is not a zip file")
zipfile.BadZipFile: File is not a zip file
```
If I open the jar file, it's actually a (Cloudflare?) error page that includes the message "The owner of this website (cdn-raw.modrinth.com) has banned your access based on your browser's signature (6e596bcc9b6c0ce7-ua53)." Given that it's a different subdomain and different browser signature, I'm not sure if it's the same issue as this one or different (though possibly related?).

**Comment by Senth** [comment]
Hi @kevinwchang, just to double-check. Which version of `mcman` do you have? Try running `mcman --version` 🙂

**Comment by kevinwchang** [comment]
Sorry, forgot to mention this is with 1.2.6:
```
$ mcman --version
minecraft-mod-manager: 1.2.6
```

**Comment by Senth** [comment]
Thanks @kevinwchang, maybe I missing something, only did a quick fix last time. I'll reopen this and have another look this weekend 🙂

**Comment by theofficialgman** [comment]
> I'm having a similar-looking problem now trying to install/update anything from modrinth:

@Senth it was working for at least a day but now I get this as well. no mod downloads are working

**Comment by Senth** [comment]
@Geometrically Just to double-check because I'm a bit confused by your statement.

Basically, this app uses `https://api.modrinth.com/api/v1/mod/P7dR8mSH/version` to check the `files`  field and use the download `url` inside there.

As an example:
```json
"files": [
    {
        "hashes": {
            "sha512": "69e708e8150efc040e90f22406df97d4d1974e933d4566fd9265293b66e22f37fcc48b80a7089f8c047e3cd70d61bccac32ba3533424218750cfe455aa5991f8",
            "sha1": "ff78c08167a3e4ea68c63dd17a2236662f98aefd"
        },
        "url": "https://cdn.modrinth.com/data/P7dR8mSH/versions/0.47.10+1.18.2/fabric-api-0.47.10%2B1.18.2.jar",
        "filename": "fabric-api-0.47.10+1.18.2.jar",
        "primary": false
    }
],
```

From what I can tell, this is the correct approach, but I might be missing something?

Or do you mean that the app should instead use the `/v1/version_file/ff78c08167a3e4ea68c63dd17a2236662f98aefd/download?hash=sha1`

**Comment by Senth** [comment]
Until I get an answer I've updated the user-agents again. This time it's using a random, but one of the latest user agents.

I've also fixed it so that the script/app should partially continue to work if this happens again in the future. It will at least not save the file if an error occurred.

I'm keeping this open for a month, if there are no further errors reported until I'll close this issue. Or if I get an answer I'll change so that the script uses Modrinth API correctly 🙂

**Comment by wafflecoffee** [comment]
@Senth Hi, your current approach is the correct one. The download route is not to be used anymore; a [Cloudflare worker](https://github.com/modrinth/sisyphus) tracks the CDN accesses now. That said, you shouldn't be needing to use random useragents anymore -- to my knowledge, we don't actually do anything with the useragents except some basic analytics, but Cloudflare may have thought that we're under attack and blocked it? I'm not sure.
Could you see if it still occurs with your old UA now? It might be one of those time-based locking things.

**Comment by Senth** [comment]
A bit late reply 😅 Thanks for confirming the correct approach @wafflecoffee.

Just did a quick test, as soon as I disabled the random user agents it stopped working, so it's definitely blocking the Python user agent. But keeping the random user agents has worked for 2 months now so closing this issue 🙂
