### ISSUE TITLE
Mod is already installed - Can't reinstall mod after manually deleting it

### ISSUE THREAD

**Issue by tokenspins** [Senth/minecraft-mod-manager#33]
When you install a mod via the mod manager and then delete it from the folder and try to install it again via the manager it says the mod is already installed.

I had thinked about an uninstall command line to delete the mod from the database as a possible solution.

**Comment by Senth** [comment]
Thanks a bunch for reporting, helps a lot when people are testing the application 🙂

I think I know what the problem is, will try to solve it this weekend.

It automatically sets the mod as inactive (= deleted) if it has been removed manually (which is the correct way of uninstalling a mod). When installing a mod it, however, doesn't check if the mod in the database is in the inactive state. Changing that should solve the issue.

**Comment by Senth** [comment]
Had some time over today, so got it fixed 🙂 Will try to fix a few other bugs before releasing another version though.
